services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always

  web:
    build:
      context: .
      args:
        UID: "${UID}" # ホストのUID
        GID: "${GID}" # ホストのGID
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    # volumes:
    #   - .:/myapp
    ports:
      - "3000:3000"
    restart: always
    tty: true
    stdin_open: true
    depends_on:
      - db
      - node # nodeサービスに依存

  node:
    image: node:20  # Node.jsのイメージを使用
    working_dir: /myapp
    volumes:
      - .:/myapp  # ホストのコードをコンテナにマウント
    command: bash -c "npm install && npm run build && tail -f /dev/null"  # npm install と buildを実行

volumes:
  postgres_volume:
